### ISSUE TITLE
Order of Ops Definition influencing if type error is thrown or not

### ISSUE THREAD

**Issue by JariNestel** [Frobeniusnorm/adt-interpreter#1]
The ordering of op definitions influences if a type mismatch error is thrown or not.
This throws `Could not match "d" (with type: "X") with expected type "Y" in operation call for "c"` as expected:
```
adt X
sorts X
ops
    d: -> X
    a: -> X
end

adt Y
sorts X, Y
ops
	c: X x Y -> Y
axs
	c(a(), c(a(), d())) = d()
end
```
But this does not:
```
adt X
sorts X
ops
    a: -> X
    d: -> X
end

adt Y
sorts X, Y
ops
	c: X x Y -> Y
axs
	c(a(), c(a(), d())) = d()
end
```

**Comment by JariNestel** [comment]
After further research I've found, that this error does not occur, when `X` has an empty (instead of no) `axs` section, even though it is said to be optional.

**Comment by Frobeniusnorm** [comment]
Should be fixed now

The problem was that when the adt did not contain an axs part, the last ops line was not read (since i forgot that the line scope of an adt does not include the end statement), so in your last example d was used as a variable (i also included an error when you try to declare a variable as a function with no arguments). I included your examples in my test cases.

Thank you very much for pointing out this bug! :)
